name: 'Artifacts restore'
description: 'Artifacts restore'
inputs:
  dotnet-version:
    description: 'The version of the dotnet'
    default: '7.0.x'
runs:
  using: 'composite'
  steps:
  -
    name: Use cached cake frosting
    id: cache-cake
    uses: actions/cache@v3
    with:
      path: run
      key: run-${{ runner.os }}-${{ hashFiles('./build/**') }}
  -
    name: Use cached tools
    id: cache-tools
    uses: actions/cache@v3
    with:
      path: tools
      key: tools-${{ runner.os }}-${{ hashFiles('./build/**') }}
  -
    uses: actions/download-artifact@v3
    name: Download gitversion tool
    with:
      name: tool
      path: ${{ github.workspace }}/dogfood
  -
    name: Setup .NET SDK
    uses: actions/setup-dotnet@v3
    with:
      dotnet-version: ${{ inputs.dotnet-version }}
