name: Homebrew

on:
  push:
    branches:
    - master
    - 'fix/*'
    - 'feature/*'

  repository_dispatch:
    types: [release]
jobs:
  homebrew:
    name: Bump Homebrew formula
    runs-on: macos-latest
    steps:
    - uses: dawidd6/action-homebrew-bump-formula@v3
      with:
        # GitHub token, required, not the default one
        token: ${{secrets.HOMEBREW_GITHUB_TOKEN}}
        # Formula name, required
        formula: gitversion
        # Optional, will be determined automatically
        tag: 5.6.1  
